
name = "mangofier"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-05"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
